build/Linux/Makefile, build/Linux/Makefile_Rev, include/epanet2.h
Won't compile without `EN_LINKQUAL` being defined in `epanet2.h`.
Also, added `-std=c99` to compiler flags in both Linux Makefiles to suppress warnings re variables being declared in for loop initialisation statements.
=> Add EN_LINKPATTERN to epanet2.h

build/CMake/CMakeLists.txt, include/epanet2.h
Couldn't get `patch-2-0-13` to build on Linux.  Fixed by 
- Ensuring that `DLL_EXPORT` is `#define`ed as the empty string on unspecified OSs (i.e. none of `WINDOWS`, `CYGWIN` or `__APPLE__` are `#define`d)
- Ensuring libm is linked to by appending it it to the `target_link_libraries` in `CMakeLists.txt`
=> Building on Linux: #define DLL_EXPORT as the empty string and link to libm

build/MinGW/Makefile, include/epanet2.h
In epanet2.h added Warnflag in exported symbols with __declspec(dllexport)  (otherwise Warnflag cannot be exported in DLL).
In this way main.c can be compiled and linked to epanet2.exe that loads epanet2.DLL (just like linux version does with libepanet2.so).
Added MingW32/Makefile for compilation with gcc under windows/mingw
=> added Warnflag in exported symbols

build/Linux/Makefile, build/Linux/runepanet.sh.template, build/MinGW/Makefile, include/epanet2.h, run/main.c, src/epanet.c, src/output.c
now Warnflag is retuned with errorcode from ENepanet function
modified main.c  
* new use of return value from ENepanet
* errcode==0  no errors, no warnings)
*  0< errcode < 100    warnings
* errcode > 100 errors
* if second argument  argv[2] is absent or null string redirects report file to stdout
* if error/warning reports error message (otherwise it can be difficult to understand because error is not reported in any other place, i.e. "File Error 302: cannot open input file.")
* added version numbering from epanet shared library (ENgetversion ) instead of hardcoded string
Updating constant CODEVERSION (found in TYPES.H) will be sufficient
* string used by main.c included in main.c (instead of text.h)
now main.c is a stand alone code and depends only from epanet2.h and epanet2.dll/.so …
=> undone Warnflag declaration due to cl.exe incompatibilities 

tools/outputapi/outputapi.c, tools/outputapi/outputapi.h
This EPANET binary file outputAPI is written in C and compiles in mingw gcc as a dll. It has been tested but not rigorously. It has approximately a dozen functions and offers convenient methods for getting different "slices" of data out of the binary file. It was developed to facilitate programmatic access to EPANET outputs to automate regression testing. Hence, it was written with thread safety and reentrancy in mind. These aspects of its implementation, however, have not been tested. 
The output API requires the programmer to manage memory for vectors of results by providing methods for allocating and freeing memory for them. The output API will likely be wrapped and used with scripting languages like Matlab, Python, and R. Other memory management strategies should therefore consider …
=> Initial commit for EPANET binary output API

include/epanet2.bas, include/epanet2.h, include/epanet2.vb, src/epanet.c, src/hydraul.c
The modifications to the code solve the issue of Energy calculations for variable speed pumps #71. 
Changes to the getenergy function (in hydraulic.c) allow to compute the
correct efficiency of variable speed pumps according to the affinity
laws.
Changes to epanet2.h and epanet.c are for retrieving the efficiency of
pumps through the ENgetlinkvalue function (code 16 for efficiency)
=> VSP efficiency + retrieving efficiency directly

README.md, ReleaseNotes2_2.md, appveyor.yml, include/epanet2.h, src/enumstxt.h, src/epanet.c, src/funcs.h, src/hydcoeffs.c, src/hydraul.c, src/hydsolver.c, src/hydstatus.c, src/inpfile.c, src/input1.c, src/input2.c, src/input3.c, src/output.c, src/quality.c, src/report.c, src/rules.c, src/text.h, src/types.h, tools/before-test.cmd, tools/before-test.sh, tools/run-nrtest.cmd, tools/run-nrtest.sh
Pressure Driven Analysis (PDA) was added as an alternative to EPANET's traditional Demand Driven Analysis (DDA) to avoid situations where demands are delivered at negative pressure. More description of how PDA was implemented is contained in the draft Release Notes for EPANET 2.2 which is also included in this PR. The new PDA option has been successfully tested against Example 1 in the paper by [Cheung et al. 2005](https://www.researchgate.net/publication/228570015_Extension_of_epanet_for_pressure_driven_demand_modeling_in_water_distribution_system) although the method used here is different from that in the paper.
=> Pressure Dependent Demands added to address issue 163

README.md, src/funcs.h, src/hydcoeffs.c, src/hydsolver.c, src/types.h, tools/before-test.cmd, tools/nrtest-epanet/report_diff.py, tools/run-nrtest.cmd
This update corrects the way that EPANET deals with flows that approach zero to avoid making its hydraulic solution matrix ill-conditioned. It also correctly accounts for the derivative of the friction factor w.r.t. flow when using the Darcy-Weisbach head loss formula. As a result of these changes the correct solution to the GESTAR1.INP and GESTAR1MOD.INP networks are now obtained (v. 2.0/2.1 produced incorrect solutions) and fewer trials are needed to solve D-W models.
These changes will result in slightly different results for the regression test suite. In the larger models, flow differences beyond the second decimal place occur for about 20% of the links. The accuracy values tracked in the Status Report will also show slight differences in most of the models. Examining results from 16 …
=> Fixes zero flow (#164) and D-W eqn. (#199) issues

include/epanet2.bas, include/epanet2.h, src/epanet.c, tests/test_net_builder.cpp
Also updates the net builder test. Take cares of #280 
In order to set the default pattern ID when setting the index to zero (for the case one wants to delete the default pattern), there is a need to use `DEFPATID` defined in [input1.c](https://github.com/OpenWaterAnalytics/EPANET/blob/dev/src/input1.c#L53). How can we make it global or should it be part of the project?
=> Add option to get\set default demand pattern

tests/test_demand_categories.cpp, tests/test_setid.cpp, tests/test_toolkit.cpp
The new test - test_save_reopen - located in `test_toolkit.cpp` produces intermittent segfaults when built in Debug configuration. See Issue #339.
=> Adding test_save_reopen, minor refactoring.

ReleaseNotes2_2.md, include/epanet2.bas, include/epanet2.h, include/epanet2.vb, include/epanet2_2.h, include/epanet2_enums.h, src/epanet.c, src/epanet2.c, src/input2.c, src/input3.c, src/project.c, src/types.h, tests/test_net_builder.cpp, tests/test_net_builder_2.cpp, win_build/WinSDK/epanet2.def
This commit adds the following network building features to the API:
1. Adds additional properties that can be set using` EN_setnodevalue`, `EN_setlinkvalue` and `EN_setoption` that now allows the API to build a complete EPANET network model from code.
2. Adds new functions` EN_setjuncdata`, `EN_settankdata`, and `EN_setpipedata` that allows one to set values for the multiple object properties with a single function call.
3. Adds a new unit test (`test_net_builder_2`) that tests these new functions.
4. Adds to the enumerated constant names in `epanet2_enums.h` and revises some v.2.2 names to make them more understandable.
=> Added additional network building features (#367)

appveyor.yml, tools/before-test.cmd, tools/run-nrtest.cmd
This PR simplifies the usage `before-test.cmd` and `run-nrtest.cmd` by introducing default arguments. The scripts can be called with no arguments and the tests will run.
=> Simplify command line arguments for reg test helper scripts

src/genmmd.c
Fix re-entrancy problems caused by the (unnecessary) use of static variables in genmmd module functions. The problems manifest as random crashes, when multiple threads perform simulations concurrently and some of the static variables can point to non-existing matrix elements.
While at it, mark most of functions static, as they are not used outside the module.
=> Fix re-entrancy problems / crashes caused by the use of static variables in functions

tests/CMakeLists.txt, tests/shared_test.hpp, tests/test_addrule.cpp, tests/test_demand_categories.cpp, tests/test_hydrqual.cpp, tests/test_net_builder_2.cpp, tests/test_node.cpp, tests/test_proj.cpp, tests/test_rprtanlys.cpp, tests/test_shared.hpp
Close #339 
Fixes a memory leak that was occurring when input files were saved and reopened as part of a unit test by separating the save and reopen into two different tests and defining a dependency between the two. 
Cleans up test build on gcc.
=> Cleaning up test build 

include/epanet2.bas, include/epanet2.def, include/epanet2.h, include/epanet2.vb, include/epanet2_2.h, include/epanet2_enums.h, src/epanet.c, src/epanet2.c, src/funcs.h, src/inpfile.c, src/input1.c, src/input2.c, src/input3.c, src/project.c, src/types.h, tests/test_comments.cpp, win_build/WinSDK/epanet2.def
This commit addresses issue #422.  It also adds a new unit test named `test_comments.cpp `to test the switch to dynamic comment strings along with the new API functions `EN_getcomment` and `EN_setcomment`.
=> Replace fixed-sized comment strings with dynamic strings

src/epanet.c, src/epanet2.c, src/epanet_py.c, src/hash.c, src/hydcoeffs.c, src/hydraul.c, src/hydsolver.c, src/hydstatus.c, src/inpfile.c, src/input1.c, src/input2.c, src/input3.c, src/mempool.c, src/output.c, src/project.c, src/quality.c, src/qualreact.c, src/qualroute.c, src/report.c, src/rules.c, src/smatrix.c, tests/CMakeLists.txt, tests/test_analysis.cpp, tests/test_curve.cpp, tests/test_net_builder.cpp, tests/test_project.cpp, tests/test_report.cpp, tests/test_toolkit.hpp
This PR fixes memory leaks and access violations occurring in test suites within the `test_toolkit` test module. 
Be advised, there are still memory leaks present, however, these leaks have been isolated to the net_builder API and are not being caused by problems with the tests themselves.
=> Fix leaky test code

CMakeLists.txt, doc/modules.dox, doc/toolkit-examples.dox, doc/toolkit-usage.dox, include/epanet2.bas, include/epanet2.def, include/epanet2.h, include/epanet2.vb, include/epanet2_2.h, include/epanet_py.h, src/epanet.c, src/epanet2.c, src/epanet_py.c, src/funcs.h, src/project.c, src/report.c, tests/test_curve.cpp, tests/test_link.cpp, tests/test_net_builder.cpp, tests/test_node.cpp, tests/test_pattern.cpp, win_build/WinSDK/epanet2.def
Adds an output argument to EN_addnode and EN_addlink that returns the index of the newly added object.
Also refactors the validity check on object ID names.
=> Return object index from EN_addnode and EN_addlink (issue #432)

ReleaseNotes2_2.md, doc/main.dox, run/CMakeLists.txt, src/epanet.c, src/epanet2.c, src/epanet_py.c, src/funcs.h, src/hash.c, src/hydcoeffs.c, src/hydraul.c, src/hydsolver.c, src/hydstatus.c, src/inpfile.c, src/input1.c, src/input2.c, src/input3.c, src/mempool.c, src/output.c, src/project.c, src/quality.c, src/qualreact.c, src/qualroute.c, src/report.c, src/rules.c, src/smatrix.c, src/types.h
This PR removes the `#ifdef _DEBUG` statements from all source files as per issue #482. It also makes minor updates to the doc files to emphasize that the speedup obtained by using MMD node re-ordering only applies to single period simulations.
=> Lrossman dev

tests/CMakeLists.txt, tests/test_pda.cpp
The most recently written unit tests for Tank Overflows and the PDA Demand Model were not being compiled nor run because their source files were never referenced in the CMakeLists script that builds the testing executable.
=> Fixes Overflow and PDA tests not being run

CMakeLists.txt, run/CMakeLists.txt, src/outfile/CMakeLists.txt
This PR has CMake build the toolkit DLL and command line executable so they are statically linked to the MS Visual C++ runtime libraries.
=> Add -MT switch for CMake Windows build

BUILDING.md, CMakeLists.txt, win_build/Makefile2.bat
The CMakeLists.txt and Makefile2.bat scripts were modified to work correctly with Visual Studio 2019 and with CMake's -A switch to specify which windows platform (Win32 or x64) to build for.
=> Build script updates

src/epanet.c
when pipes are deleted via deletelink it also deletes comment of last link
Co-Authored-By: Pavlos Pavlou <pavlou.v.pavlos@ucy.ac.cy>
=> fix in EN_deleteLink

src/project.c
I was pretty surprised to find this behavior - but it showed up while running lots of independent simulations serially under the same process - the OS (Mac/*nix) said it reached the open-file limit.  Investigation revealed that `mkstemp` returns a file descriptor ready for r/w - even though epanet later opens this file under a different handle, closes the second handle, and removes the file - without closing the (leaked) descriptor.
This workaround uses `mkstemp` to only create the file name from the template provided. The temp file created is closed and unlinked.
=> fixes use of mkstemp and associated file-descriptor-leaking behavior

src/project.c
=> reverts posix include

src/epanet.c, tests/test_node.cpp
See issue #542 . Also modifies unit test test_node to check that fixup works.
=> Fixes problems with EN_addnode()

src/project.c
First surfaced by @ernestoar - thanks!
The freedata function used cached values for sizes of certain arrays found in the parser struct. However, now that the network is mutable, those values can become invalid. Relying instead on the actual array lengths prevents this function from freeing unallocated memory, or ignoring cleanup on newly created elements.
=> fixes a crashing issue in freedata

doc/input-file.dox
There was a character ’ instead of ' which created an error when compiling LaTeX.
=> Incorrect character causing a LaTeX compilation problem

src/epanet.c
The EN_settimeparam function in the v2.2 toolkit API can be used to set time parameters; however, it does not allow the start time (EN_STARTTIME) to be set. This pull request adds an additional case to enable the start time to be set.
Closes #588
=> Allow start time to be set with EN_settimeparam

src/epanet.c, src/hydraul.c, src/project.c, src/smatrix.c, src/types.h
`Smatrix` allocates and frees `sm->Degree` inside of `factorize()`, but uses it in `growlist()` where it is no longer valid.
I move the allocate `sm->Degree` to `allocsmatrix()` where we already have `Nnodes`, and the free to `freesparse()` where everything else in `Smatrix` is being free'd.
---
In test_pda.cpp, `EN_getnodevalue(EN_DEMANDDEFICIT)` reads from three members of hyd (`DemandFlow`, `NodeDemand`, `EmitterFlow`) however two of these members (`DemandFlow`, `EmitterFlow`) are only valid between `EN_openH` and `EN_closeH`, which are both called in `EN_solveH`.
I add `EN_solve_openedH`, implement `EN_solveH` in terms of it, and call it instead in test_pda.cpp
I'm not sure whether this is the best way forward for this issue, though. It would make more sense to me to do away with …
=> Fix use-after-free in Smatrix, test_pda

.gitignore, include/epanet2_enums.h, src/epanet.c, src/hydcoeffs.c, src/hydraul.c, src/inpfile.c, src/input3.c, src/text.h, src/types.h
This commit solves issue #532 to allow modelling the power consumption of a number of parallel identical pumps (specified by the integer variable `GroupCount` in the pump object `SPump` operating at different relative speeds `s` following the approach given by @LRossman. The code was tested on a simple network with the topology shown below.
The pump characteristics were measured by recording pressure heads in nodes `R1` and `J1` for different values of demands set in node `J1`.
The network was simulated with one pump and two pumps in parallel operating with `s=1.0` and `s=0.75` respectively. The results form OWA EPANET (marked as points) were compared against calculations "by hand" in MATLAB/OCTAVE (marked with lines). 
First, the scaling of pump curves was tested for the pump type: …
=> Dev issue #532

src/errors.dat, src/input2.c, src/project.c
This fix solves the unconnected nodes garbled error message (Issue #608 ) and optionally adds an improved specific error message (number 2331) similar to the text in EPANET 2.1 when a network has unconnected nodes.
Another similar case in the code was found and corrected with the same pattern, but could not be tested.
=> Fix Unconnected nodes garbled error message 

src/epanet.c
Makes EN_setlinkvalue consistent with how an input file is read. This addresses issue #616 .
=> Allow negative EN_SETTING value in EN_setlinkvalue

ReleaseNotes2_3.md, src/epanet.c
Allows setting the time of day when a simulation begins.
=> Add EN_STARTTIME to EN_settimeparam function

include/epanet.cs
Hi, If you look at ENaddlink in epanet2.C, the parameters are: char *id, int linkType, char *fromNode, char *toNode, int *index.
So the last parameter needs to be an integer.
Similar case for other changes.
=> Method parameter types need to match definitions in epanet2.c

src/epanet.c
Fixes a bug where 0 was not considered to be a valid pattern index.
=> Bugfix for En_getaveragepatternvalue() and Return MISSING initial setting from EN_getlinkvalue()

src/hydraul.c, src/input3.c
Fixes a possible integer overflow when computing time for a tank to fill/empty (issue #666 ). Also fixes issue #642 that failed to set a pump's initial setting to 0 when its initial status was CLOSED.
=> Fixes possible integer overflow

src/inpfile.c
EN_saveinpfile was incorrectly saving the index of the GPV head loss curve inside of a simple control instead of the control status
This is a fix for #671
=> Fix for GPV controls in EN_saveinpfile

doc/toolkit-usage.dox
EN_geterror doesn't take in the project wrapper, and you need to include maxLen.
Stumbled on this when I was copying the example from: http://wateranalytics.org/EPANET/toolkit-usage.html
=> Bug in example code for detecting error conditions

src/input2.c
under some circumstances, like certain input lines that have long comments, the code here can cause an underflow in size_t which casts to a very large integer during comparison and results in the number of tokens being over-reported (max of 40). Most of these tokens are of course garbage. Changing this `len` variable to an integer permits it to be less than zero, thus allowing an exit from the `while` at L665.
=> fixes issue where a string position causes underflow

src/hydcoeffs.c
Fixes possible loss of network connectivity for an active pressure sustaining valve that can affect the validity of a hydraulic solution (see issue #692).
=> Preserves network connectivity across an active PSV

include/epanet2.h, include/epanet2_2.h, src/epanet.c, src/epanet2.c, src/project.c, src/report.c, src/types.h
This addition should be viewed as a helpful counterpart to the `pviewprog` callback that can be passed into the `ENepanet` function, but with the inclusion of the project handle and a user-supplied context pointer. If the user supplies a reporting callback, their function will be called each time EPANET wants to log anything that used to go into the report file.
=> adds client callback API function

src/inpfile.c, src/input3.c
Ignores errors when reading node & link vertex coordinates from an input file. Also when saving a project to an input file, the [DEMANDS] section only includes non-zero demands. See issues #603 and #174 .
=> Ignore errors in coords. read from file

ReleaseNotes2_3.md, doc/input-file.dox, include/epanet.cs, include/epanet2.bas, include/epanet2.pas, include/epanet2.vb, include/epanet2_enums.h, src/enumstxt.h, src/epanet.c, src/hydcoeffs.c, src/inpfile.c, src/input1.c, src/input3.c, src/text.h, src/types.h
Adds a global hydraulic option to allow back flow or not through emitter elements. To maintain backward compatibility the default is YES. See issue #659.
=> Add emitter backflow option

src/input3.c
If you create a simple control with nine or more input tokens, the logic skips over assigning the hour variable and EPANET will activate the control at hour zero.
Fixes #709
=> Fixes incorrect hour set with >9 input tokens for simple controls

doc/input-file.dox, doc/toolkit-units.dox, include/epanet.cs, include/epanet2.bas, include/epanet2.pas, include/epanet2.vb, include/epanet2_enums.h, src/enumstxt.h, src/epanet.c, src/input1.c, src/input3.c, src/outfile/include/epanet_output_enums.h, src/outfile/src/epanet_output.c, src/text.h, src/types.h, tests/test_demand.cpp
I've added support for cubic meters per second, the tests are very basic and cover the most simple cases.
I haven't modified anything under `src/outfile` but can push another commit if we want to update and there is support for adding CMS flow units into EPANET.
Fixes #712
=> Add support for cubic meters per second (CMS)

src/epanet.c, src/project.c
simple omission bug preventing use of setlinkvalue for EN_GPV_CURVE when the link is not a GPV.
=> setlinkvalue missing a break statement

ReleaseNotes2_3.md, src/report.c
The function getclosedlink in report.c uses recursion to find closed links when reporting on disconnections.
In very large networks, it’s possible for the recursion to exhaust the memory on the call stack which then causes EPANET to crash.
If a loop is used instead of recursion, EPANET will not crash with very large disconnections
Fixes #737
=> Remove recursion in getclosedlink

include/epanet2.bas, include/epanet2.cs, include/epanet2.def, include/epanet2.h, include/epanet2.pas, include/epanet2.vb, include/epanet2_2.h, src/epanet.c, src/epanet2.c, src/errors.dat, src/funcs.h, src/hydraul.c, src/input1.c, src/input2.c, src/input3.c, src/project.c, src/rules.c, src/validate.c
`EN_openX() `allows an EPANET input file to be opened even if it has errors. This required re-arranging code, mainly in input3.c, so that default values are assigned to an object before its input line is parsed. Also a new function, `validateproject()`, placed in the new code module validate.c, is used to check for valid tank levels and pump curve coefficients that were formerly made in input2.c.
=> Add EN_openX function

ReleaseNotes2_3.md, src/text.h
=> Update release notes and remove depreciated constants

BUILDING.md, CMakeLists.txt, conanfile.py
additionally, this PR adds install target locations and an optional cmake def for building epanet as a static library - `-DBUILD_SHARED_LIBS=OFF` as these are common cmake conventions.
=> Fixes conan build, adds documentation for this option

src/epanet.c
The pipe counter was not decreased if the element was a pipe.
=> Fix Issue #790 - incorrect number of pipes

src/hydraul.c, src/quality.c
This is the proposed fix for Issue #789. 
It is the fastest and most straightforward solution I could think of. The only drawback is the freeing of Adjlist between hydraulics and quality simulations.
Alternatively, one could think of invalidating and freeing it whenever an element (node or a link) is added to the network.
=> Fix Issue #789 - free network Adjlist

ReleaseNotes2_3.md, src/epanet.c
Thank you @LRossman for finding the solution to this issue
Fixes #795
=> Fix emitter-related NaN errors from EN_setnodevalue API

src/inpfile.c, src/input3.c, src/text.h
This change avoids a conflict between the EMITTER EXPONENT and EMITTER BACKFLOW keywords when running a v2.3 input file in the v2.2 EPANET GUI.
=> Changes EMITTER BACKFLOW keyword

ReleaseNotes2_3.md, include/epanet2.h, include/epanet2_2.h, src/epanet.c, src/epanet2.c
Adds methods for batch requesting node and link property values, see #785 for details.
=> add ENgetnodesvalues and ENgetlinksvalues methods

src/hydraul.c, src/quality.c
In the previous PR, I added the `freeadjlists(pr)` in the hydraulic and quality close function. However, the function needs a pointer to a network.
=> Fix Issue 789- PR 791 

src/epanet2.c, src/report.c
Fixes problem with incompatible argument types in the legacy API functions `ENgetnodevalues `and `ENgetlinkvalues`.
=> Fix two legacy API functions

src/inpfile.c
This commit includes the following changes:
- Column headings have been added for each section in the INP file.
- The alignment of the values has been updated to match these headings.
These enhancements improve readability and understanding of the INP file.
=> feat: Add column headings for sections in INP file

src/qualreact.c
Fixes volume remaining in mixing zone when there is net outflow from a 2-compartment tank.
=> Corrections to 2-compartment tank mixing

src/inpfile.c, src/input3.c, src/rules.c, src/text.h
=> Add read/write of disabled controls to input file

README.md, run/main.c, src/hash.c, src/hash.h, src/hydcoeffs.c, src/hydsolver.c, src/hydstatus.c, src/mempool.c, src/mempool.h, src/output.c, src/qualreact.c, src/smatrix.c
Avoid confusion about to which version a source code file belongs.
=> Replace 2.2 with 2.3 in file headings

ReleaseNotes2_3.md, include/epanet2.bas, include/epanet2.cs, include/epanet2.pas, include/epanet2.vb, include/epanet2_enums.h, src/enumstxt.h, src/epanet.c, src/input1.c, src/input3.c, src/text.h, src/types.h, tests/test_units.cpp
This PR decoupled pressure units from the flow unit system, allowing them to be set independently to support mixed-unit conventions (e.g., using LPS for flow and PSI for pressure).
In Canada infrastructure is built using the metric system however many operators and utilities still refer to pressure in PSI.
This update would allow pressure units to be mix either when `PRESSURE` in the `[OPTIONS]` section of the INP is defined, or if the user uses `EN_getoption` and `EN_PRESS_UNITS`.
To keep backwards compatibility the use of `EN_setflowunits` also changes the pressure units to either `METERS` or `PSI` to match the flow unit type.
=> Decoupled pressure units from the flow unit system

src/epanet.c
This change recognizes that when setting the initial status of a link (`EN_INITSTATUS`) using the toolkit function `EN_setlinkvalue`, the only valid values for it are 0 (`EN_CLOSED`) and 1 (`EN_OPEN`). The previous code also allowed a value of 2 for `ACTIVE`, but that should only apply to valve links and there is no` EN_ACTIVE` constant defined in the toolkit. A comment has been added to the code noting that to make the initial status of a valve `ACTIVE` one should assign a value to the valve's `EN_INITSETTING` property.
=> Update EN_setlinkvalue for EN_INITSTATUS
