src/epanet.c

node coordinates deallocation added in freedata()

issue #44 memory leak

---

.mailmap
.travis.yml
AUTHORS
build/CMake/CMakeLists.txt
build/Xcode/epanet.xcodeproj/project.pbxproj
tests/compare_enb.py
tests/test_networks.sh

stubbing out some test scripts. this works with travis.

Dev 2.1 test network script

---

include/epanet2.h

EN_TANKCOUNT is for both tanks and reservoirs.

Added reservoirs in EN_TANKCOUNT header comment

---

include/epanet2.bas
include/epanet2.h
include/epanet2.vb
src/epanet.c
src/inpfile.c
src/rules.c
src/text.h
src/types.h

The modifications below allow rule based controls to be changed using the functions in the dll. The additional function that writes the rules in the .inp file has been modified to write "TANK" or "JUNCTION" instead of the generic "NODE" as suggested a while ago by @eladsal (and similarly for LINK).
I am attaching a guide to the functions in case it is useful. The guide is the same as the additional material to the journal paper (http://ascelibrary.org/doi/abs/10.1061/%28ASCE%29WR.1943-5452.0000637): there are minor changes in the names of the variables compared to the version below.
[Appendix C_GuideToRuleBasedControlFunctions_rev2.docx](https://github.com/OpenWaterAnalytics/EPANET/files/488835/Appendix.C_GuideToRuleBasedControlFunctions_rev2.docx)
Please, let me know if there are …

Changing rule based

---

README.md

I've added this link here, but perhaps it could move to a different location to do this as well (the wiki?).

Added the link to the step-by-step tutorial

---

include/epanet2.h
src/epanet.c
src/funcs.h
src/hash.c
src/hash.h
src/inpfile.c
src/input2.c

Added ENaddnode, ENaddlink, ENremovenode and ENremovelink functions to change the network.
Added ENinit function to start a new network from scratch

Add functions for creating and changing networks

---

README.md

Also testing CI github integration still

Updated Appveyor Badges [default dev branch]

---

CMakeLists.txt

also much improved IDE file grouping, for people who use IDEs

modifies cmake to link shared lib to the CLI

---

tools/before-test.cmd
tools/before-test.sh
tools/run-nrtest.cmd
tools/run-nrtest.sh

Closes #170 
Badge is now green on Appveyor!

Migrating to benchmark 2012vs10

---

.travis.yml
appveyor.yml

Fixes Appveyor and Travis.  Addresses optional build of tests - Issue #186.

Adding cmake variable BUILD_TESTS to Appveyor and Travis

---

src/epanet.c
tests/test_toolkit.cpp

The fix is simple but this is my first test so please review.

Fix EN_addpattern and add test for the function

---

src/epanet.c
win_build/WinSDK/epanet2.def

Add legacy ENinit API and set status for new links in EN_addlink

---

include/epanet2.bas
include/epanet2.h
src/epanet.c
tests/test_toolkit.cpp
win_build/WinSDK/epanet2.def

Add EN_addcontrol function

---

src/epanet.c

Fixes error messages

---

tests/test_output.cpp

Fixing memory leak

---

ReleaseNotes2_2.md
src/inpfile.c
src/input3.c
src/types.h

Take cares of #290 .
Also added placeholders for new API functions, general changes, new definitions and list of contributing authors. Related to #289.

Read and write the demand categories names

---

include/epanet2.bas
include/epanet2.h
include/epanet2.vb
src/epanet.c

Also, add `Public Const EN_DEMANDDEFPAT = 7` in the file `epanet2.vb`.

add option EN_HEADLOSSFORM in function ENgetoption

---

ReleaseNotes2_2.md
include/epanet2.bas
include/epanet2.h
src/epanet.c
tests/test_demand_categories.cpp
win_build/WinSDK/epanet2.def

Added APIs to get and set the demand categories names. Also added a test for the new functions.
Relates to #294

Add demand names get\set APIs

---

appveyor.yml

Saves SUT benchmark as build artifact on Appveyor 

---

ReleaseNotes2_2.md
include/epanet2.bas
include/epanet2.h
include/epanet2.vb
src/epanet.c
tests/test_setlinktype.cpp

- Complete rewrite of EN_setlinktype with link index argument passed by reference
- New unit test of EN_setlinktype added
- New function EN_setlinknodes added

Rewrite of EN_setlinktype function (#305)

---

include/epanet2.bas
include/epanet2.h
include/epanet2.vb
src/epanet.c
src/funcs.h
src/rules.c
src/types.h

- Also adds new API function EN_deletecontrol
- Updates and re-arranges entries in the VBA and VB.Net headers

Fixes bug #172 (adjust controls & rules when node/link added or deleted)

---

src/epanet.c
win_build/WinSDK/epanet2.def

Add ENsetlinknodes to DEF file and add a function check

---

tests/test_output.cpp

Fix test_output check_cdd()

---

include/epanet2.vb
include/epanet2_2.h
include/epanet2_enums.h
src/epanet.c
src/hydsolver.c
src/inpfile.c
src/input3.c
src/project.c
src/quality.c
src/qualreact.c
src/qualroute.c
src/report.c
src/rules.c
src/smatrix.c
src/types.h
tests/test_net_builder_2.cpp

In addition to addressing compiler warnings, argument names in the API function prototypes were made more consistent and descriptive. Also additional Doxygen comments were added in preparation for producing a more thorough documentation of the API.

New updates to address compiler warnings (issue #370)

---

include/epanet2.bas
include/epanet2.h
include/epanet2.vb
include/epanet2_2.h
src/epanet.c
src/epanet2.c
win_build/WinSDK/epanet2.def

Add new function to get and set title strings

---

ReleaseNotes2_2.md
doc/modules.dox
include/epanet2.bas
include/epanet2.def
include/epanet2.h
include/epanet2.vb
include/epanet2_2.h
src/epanet.c
src/epanet2.c
src/funcs.h
src/project.c
src/report.c
tests/test_pattern_curve_funcs.cpp

1. Adds `EN_deletepattern, EN_setpatternid, EN_deletecurve, EN_setcurveid`, and `EN_copyreport` functions, along with their single threaded counterparts, to the API.
2. Adds a test file for the new pattern and curve functions.
3. Updates the .def and VB header files for the new functions.
4. Fixes crash caused by `EN_open -- EN_close -- EN_init` sequence of calls.
5. Updates documentation files.

Adds new pattern, curve and reporting functions to API

---

CMakeLists.txt
appveyor.yml

Fixes 64-bit build on Windows

---

src/epanet.c
src/funcs.h
src/project.c
src/quality.c
src/report.c

Second attempt to have commits implementing this feature pass the CI checks (local tests are successful).

Give external apps access to binary output file (#407)

---

.travis.yml
tools/before-test.sh

PR #401 broke coverage. This PR restores it.

Restores coverage

---

tests/test_hydrqual.cpp
tests/test_node.cpp
tests/test_output.cpp
tests/test_shared.hpp
tools/epanet-output/CMakeLists.txt
tools/epanet-output/include/epanet_output.h
tools/epanet-output/include/epanet_output_enums.h
tools/epanet-output/src/epanet_output.c
tools/epanet-output/src/epanet_output.i

Adds test for access to binary output file prior to project close.

Add access test to test_output.cpp

---

src/project.c
src/util/filemanager.c
src/util/filemanager.h
tests/test_link.cpp
tests/util/test_errormanager.cpp
tests/util/test_filemanager.cpp

This PR fixes several warnings that occur when building with gcc.

Cleaning up build on gcc

---

include/epanet2.bas
include/epanet2.vb
include/epanet2_enums.h
src/epanet.c
src/inpfile.c
src/input1.c
src/input2.c
src/types.h
tests/test_analysis.cpp
tests/test_net_builder.cpp
tests/test_pattern.cpp

See issue #429. Also allowed the EN_HEADLOSSFORM option to be changed if the solver is not active.

Removed the EN_DEFDEMANDPAT option

---

README.md
src/util/list.c
src/util/list.h
tests/CMakeLists.txt
tests/util/CMakeLists.txt
tests/util/test_errormanager.cpp
tests/util/test_list.cpp

See Issue #452
Straight forward to use. Tests with no memory leaks.

Dev generic list

---

src/report.c
tools/nrtest-epanet/nrtest_epanet/__init__.py

This may fail the CI tests since it modifies the status report -- we'll see.

Minor format change to status report

---

ReleaseNotes2_2.md
doc/input-file.dox
include/epanet2.bas
include/epanet2.vb
include/epanet2_enums.h
src/enumstxt.h
src/epanet.c
src/hydstatus.c
src/inpfile.c
src/input3.c
src/report.c
src/text.h
src/types.h
tests/test_overflow.cpp

This PR addresses part of Issue #35 and includes a unit test case.

Adds tank overflow feature

---

src/epanet.c

Co-Authored-By: Andreas Ashikkis <andreasashikkis@users.noreply.github.com>

Fix EN_getElseaction and EN_setelseaction

---

src/epanet.c

Fixes EN_setlinkvalue bug

---

src/funcs.h
src/hydcoeffs.c
src/project.c

Fixes bugs in pump and demand head loss gradients

---

include/epanet2.bas
include/epanet2.def
include/epanet2.h
include/epanet2.pas
include/epanet2.vb
include/epanet2_2.h
src/epanet.c
src/epanet2.c
src/hydraul.c
src/input3.c
src/project.c
src/types.h

See issue #546 . Also fixes a small bug in project.c.

Adds EN_getresultindex function to the API

---

include/epanet2.pas
src/epanet.c
src/epanet2.c
src/funcs.h
src/project.c

Adjusts params of any pump that uses the curve whose data is modified by EN_setcurve or EN_setcurvevalue (issue #550 ).

Bug fix for EN_setcurve

---

doc/modules.dox
include/epanet2.bas
include/epanet2.pas
include/epanet2.vb
include/epanet2_enums.h
src/epanet.c

Addresses issues #552 and #553

EN_getrule bug fix and EN_MISSING addition

---

include/epanet2.pas
src/epanet.c

Adds error check to EN_setheadcurveindex

---

src/epanet.c
src/funcs.h
src/input3.c
src/project.c

Bug fix for valvecheck function

---

src/hydraul.c

See latest comments in issue #528. Also, the `setlinkflow()` function was deleted as it was never called anywhere.

Fixes problem with re-opening const. HP pumps

---

LICENSE

Small edit to the license.txt file.

Adding text, "list of authors," to license file

---

src/epanet.c

Co-Authored-By: Lew Rossman <lrossman@outlook.com>
Co-Authored-By: Elad Salomons <selad@optiwater.com>
#583

fix EN_INITSETTING

---

src/epanet.c

Fix EN_settankdata for elevation with SI units

---

src/epanet.c

Correct vmin calculations

---

include/epanet2.bas

Add comments APIs to VB bas include file

---

src/hydcoeffs.c
src/hydstatus.c

Empty tank draining fix

---

src/input3.c

Fix check for roughness coefficient

---

src/input1.c

This commit addresses Issue #650.

Removes silent change to WQ option for 0 duration run

---

include/epanet2_enums.h
src/epanet.c
src/hydraul.c
src/inpfile.c
src/input1.c
src/types.h
tests/test_node.cpp

Fix for getting/setting/saving default demand pattern option

---

ReleaseNotes2_3.md
src/hydcoeffs.c
src/hydsolver.c
tools/nrtest-epanet/nrtest_epanet/__init__.py
tools/nrtest-epanet/setup.py
tools/run-nrtest.cmd
tools/run-nrtest.sh
tools/test-config.sh

Small change to improve PDA convergence.

Dev pda mod

---

src/hydcoeffs.c

Modifies how the head loss and its gradient are computed for the tails of a constant HP pump curve.

Modify const. HP pump

---

ReleaseNotes2_3.md
src/hydstatus.c

Fixes Possible Incorrect Solution for Flow Control Valves

---

conanfile.py

Conan is a great C/C++ package manager that lets other projects simply pull in a git URL and build up their dependencies.

Creates conanfile.py

---

ReleaseNotes2_3.md
doc/input-file.dox
include/epanet.cs
include/epanet2.bas
include/epanet2.pas
include/epanet2.vb
include/epanet2_enums.h
src/enumstxt.h
src/epanet.c
src/funcs.h
src/hydcoeffs.c
src/hydraul.c
src/inpfile.c
src/input3.c
src/output.c
src/project.c
src/text.h
src/types.h
tests/CMakeLists.txt
tests/test_valve.cpp

This PR is in response to the recent discussion in issue #18 . In addition to code updates that implement the new PCV valve, a new unit test for a PCV was added and the input file format section of the project's documentation (input-file.dox) was updated.

New positional control valve added

---

include/epanet2.h
include/epanet2_2.h
src/epanet.c
src/epanet2.c
src/funcs.h
src/hash.c
src/hash.h
src/project.c
src/report.c
src/types.h

See issue #651. Also addresses issue #602.

Allows string literals as arguments in C++ clients

---

src/hydstatus.c

Simplifies status check for links connected to full/empty tanks and now includes case where link connects two tanks.

Revise status test for full/empty tanks

---

src/hydcoeffs.c

Uses continuous barrier functions to constrain PDA demands and emitter flows to allowable values (see J. Hydroinformatics, 24:697, 2022).

Use barrier functions for PDA & emitters

---

src/epanet.c
src/project.c

fixes a bug in adjustpumpparams().

Adjustpumpparams bugfix

---

ReleaseNotes2_3.md
include/epanet.cs
include/epanet2.bas
include/epanet2.pas
include/epanet2.vb
include/epanet2_enums.h
src/epanet.c
src/funcs.h
src/inpfile.c
src/project.c
src/types.h

Allow simple controls to set valves OPEN/CLOSED

---

ReleaseNotes2_3.md
include/epanet2.bas
include/epanet2.cs
include/epanet2.pas
include/epanet2.vb
include/epanet2_enums.h
src/epanet.c

Added retrieval of emitter flow to the API

---

include/epanet2.pas
src/hydcoeffs.c
src/input3.c
tests/test_valve.cpp

Change PCV settings from fraction to percent

---

ReleaseNotes2_3.md
include/epanet2.pas
src/input3.c

This PR addresses issue #749 .

Fix trace node id parser error

---

ReleaseNotes2_3.md
include/epanet2.h
include/epanet2_2.h
include/epanet2_enums.h
src/epanet.c
src/epanet2.c
src/hydraul.c
src/input3.c
src/project.c
src/rules.c
src/types.h

As discussed long ago in the Issues tracker. I've added old-style api stubs as well for this functionality.

adds api support for enabling/disabling controls and rules

---

include/epanet2.bas
include/epanet2.cs
include/epanet2.def
include/epanet2.pas
include/epanet2.vb

Updated header files following #751

Updated header files following #751

---

src/qualreact.c

This change addresses issue #769.

Account for mass lost in tank overflow

---

.github/workflows/ccpp.yml
.github/workflows/macos.yml
.github/workflows/win32.yml
.github/workflows/win64.yml
CMakeLists.txt
README.md
win_build/Makefile.bat

Update old build script with validate.c file

Update old build script

---

src/project.c

Close scratch hydraulics file between runs

---

ReleaseNotes2_3.md
include/epanet2.bas
include/epanet2.cs
include/epanet2.def
include/epanet2.h
include/epanet2.pas
include/epanet2.vb
include/epanet2_2.h
include/epanet2_enums.h
src/epanet.c
src/epanet2.c
src/funcs.h
src/inpfile.c
src/input2.c
src/input3.c
src/mempool.c
src/project.c
src/quality.c
src/qualroute.c
src/report.c
src/types.h
tests/test_node.cpp

Adds EN_gettag and EN_settag functions to the Toolkit

---

src/enumstxt.h
src/inpfile.c
src/input3.c
src/text.h

Include curve type in input file

---

src/epanet.c
src/hydraul.c
src/inpfile.c
src/input1.c
src/input3.c
src/types.h

InitSetting added to Link struct

---

src/epanet.c

Fix Trace Node bug

---

src/epanet.c
src/hydraul.c
src/report.c
src/text.h
src/types.h

Fix set EN_INITSETTING and EN_INITSTATUS

---

src/epanet.c
src/types.h

Fixes bug in EN_setpipedata
